# Generated by Django 5.2.3 on 2025-06-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmapp', '0002_technician_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.TextField(default='Not Provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone1',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
